"""initial schema

Revision ID: 508a25128b6c
Revises:
Create Date: 2026-09-30 08:10:30.465341

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "508a25128b6c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semana_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("semana_event_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_deleted_at_idx"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_table(
        "atividades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semana_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "PALESTRA",
                "WORKSHOP",
                "ENCERRAMENTO",
                "CONVERSA",
                "COFFEE_BREAK",
                name="tipoatividade",
            ),
            nullable=False,
        ),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PROVISORIA", "CONFIRMADA", name="statusatividade"),
            nullable=False,
        ),
        sa.Column("comeca_as", sa.DateTime(timezone=True), nullable=False),
        sa.Column("termina_as", sa.DateTime(timezone=True), nullable=False),
        sa.Column("codigo", sa.String(length=4), nullable=False),
        sa.Column("pontos", sa.Integer(), nullable=False),
        sa.Column("horas", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["semana_id"],
            ["semana_event.id"],
            name=op.f("atividades_semana_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("atividades_pkey")),
        sa.UniqueConstraint("semana_id", "codigo", name="uq_atividade_semana_codigo"),
    )
    op.create_index(
        op.f("atividades_deleted_at_idx"), "atividades", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("atividades_semana_id_idx"), "atividades", ["semana_id"], unique=False
    )
    op.create_index(
        "ix_atividade_semana_schedule",
        "atividades",
        ["semana_id", "comeca_as"],
        unique=False,
    )
    op.create_table(
        "challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("prompt", sa.String(length=5000), nullable=False),
        sa.Column(
            "scoring_type",
            sa.Enum(
                "QUIZ",
                "INPUT",
                "MANUAL",
                name="challengescoringtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("image_path", sa.String(length=512), nullable=True),
        sa.Column("resource_urls", sa.JSON(), nullable=False),
        sa.Column("points_value", sa.Integer(), nullable=False),
        sa.Column("input_answer", sa.String(length=255), nullable=True),
        sa.Column("semana_id", sa.Integer(), nullable=True),
        sa.Column(
            "finishes_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + interval '1 day'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["semana_id"], ["semana_event.id"], name=op.f("challenges_semana_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("challenges_pkey")),
    )
    op.create_index(
        op.f("challenges_deleted_at_idx"), "challenges", ["deleted_at"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("refresh_tokens_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("refresh_tokens_pkey")),
        sa.UniqueConstraint("token_hash", name=op.f("refresh_tokens_token_hash_key")),
    )
    op.create_table(
        "semana_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semana_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["semana_id"],
            ["semana_event.id"],
            name=op.f("semana_participants_semana_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("semana_participants_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("semana_participants_pkey")),
        sa.UniqueConstraint(
            "semana_id", "nickname", name="uq_semana_participant_nickname"
        ),
        sa.UniqueConstraint(
            "semana_id", "user_id", name="uq_semana_participant_event_user"
        ),
    )
    op.create_index(
        op.f("semana_participants_deleted_at_idx"),
        "semana_participants",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "challenge_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column("semana_participant_id", sa.Uuid(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submission", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
            name=op.f("challenge_participants_challenge_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["semana_participant_id"],
            ["semana_participants.id"],
            name=op.f("challenge_participants_semana_participant_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("challenge_participants_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("challenge_participants_pkey")),
        sa.UniqueConstraint(
            "user_id", "challenge_id", name="uq_participant_user_challenge"
        ),
    )
    op.create_index(
        op.f("challenge_participants_deleted_at_idx"),
        "challenge_participants",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "point_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("semana_participant_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["semana_participant_id"],
            ["semana_participants.id"],
            name=op.f("point_events_semana_participant_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("point_events_pkey")),
        sa.UniqueConstraint(
            "semana_participant_id",
            "source_type",
            "source_id",
            name="uq_point_event_source",
        ),
    )
    op.create_index(
        op.f("point_events_deleted_at_idx"),
        "point_events",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "presencas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("atividade_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("horas", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["atividade_id"],
            ["atividades.id"],
            name=op.f("presencas_atividade_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("presencas_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("presencas_pkey")),
        sa.UniqueConstraint(
            "atividade_id", "email", name="uq_presenca_atividade_email"
        ),
        sa.UniqueConstraint(
            "atividade_id", "user_id", name="uq_presenca_atividade_user"
        ),
    )
    op.create_index(
        op.f("presencas_atividade_id_idx"), "presencas", ["atividade_id"], unique=False
    )
    op.create_index(
        op.f("presencas_deleted_at_idx"), "presencas", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("presencas_user_id_idx"), "presencas", ["user_id"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prompt", sa.String(length=5000), nullable=False),
        sa.Column("answer", sa.String(length=255), nullable=False),
        sa.Column("points_value", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
            name=op.f("questions_challenge_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("questions_pkey")),
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.String(length=255), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["challenge_participants.id"],
            name=op.f("answers_participant_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("answers_question_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("answers_pkey")),
        sa.UniqueConstraint(
            "participant_id", "question_id", name="uq_participant_question"
        ),
    )
    op.create_index(
        op.f("answers_deleted_at_idx"), "answers", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("answers_deleted_at_idx"), table_name="answers")
    op.drop_table("answers")
    op.drop_table("questions")
    op.drop_index(op.f("presencas_user_id_idx"), table_name="presencas")
    op.drop_index(op.f("presencas_deleted_at_idx"), table_name="presencas")
    op.drop_index(op.f("presencas_atividade_id_idx"), table_name="presencas")
    op.drop_table("presencas")
    op.drop_index(op.f("point_events_deleted_at_idx"), table_name="point_events")
    op.drop_table("point_events")
    op.drop_index(
        op.f("challenge_participants_deleted_at_idx"),
        table_name="challenge_participants",
    )
    op.drop_table("challenge_participants")
    op.drop_index(
        op.f("semana_participants_deleted_at_idx"), table_name="semana_participants"
    )
    op.drop_table("semana_participants")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("challenges_deleted_at_idx"), table_name="challenges")
    op.drop_table("challenges")
    op.drop_index("ix_atividade_semana_schedule", table_name="atividades")
    op.drop_index(op.f("atividades_semana_id_idx"), table_name="atividades")
    op.drop_index(op.f("atividades_deleted_at_idx"), table_name="atividades")
    op.drop_table("atividades")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_index(op.f("users_deleted_at_idx"), table_name="users")
    op.drop_table("users")
    op.drop_table("semana_event")
    # ### end Alembic commands ###
