"""challenges cover image

Revision ID: 597d02678cf0
Revises: 7b14a96d2c83
Create Date: 2026-09-27 21:30:55.360689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597d02678cf0'
down_revision: Union[str, Sequence[str], None] = '7b14a96d2c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('image_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'image_path')
    # ### end Alembic commands ###
