"""challenges tables

Revision ID: c8389c55b075
Revises: dd4ca2ff096e
Create Date: 2026-09-27 00:27:26.225175

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8389c55b075"
down_revision: str | Sequence[str] | None = "dd4ca2ff096e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "scoring_type",
            sa.Enum(
                "QUIZ",
                "MANUAL",
                name="challengescoringtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("challenges_pkey")),
    )
    op.create_index(
        op.f("challenges_deleted_at_idx"), "challenges", ["deleted_at"], unique=False
    )
    op.create_table(
        "username_mothers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=201), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("username_mothers_pkey")),
        sa.UniqueConstraint("full_name", name=op.f("username_mothers_full_name_key")),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prompt", sa.String(length=5000), nullable=False),
        sa.Column("answer", sa.String(length=255), nullable=False),
        sa.Column("points_value", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
            name=op.f("questions_challenge_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("questions_pkey")),
    )
    op.create_table(
        "usernames",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=False),
        sa.Column("first_mother_id", sa.Uuid(), nullable=False),
        sa.Column("last_mother_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["first_mother_id"],
            ["username_mothers.id"],
            name=op.f("usernames_first_mother_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["last_mother_id"],
            ["username_mothers.id"],
            name=op.f("usernames_last_mother_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("usernames_pkey")),
        sa.UniqueConstraint("nickname", name=op.f("usernames_nickname_key")),
    )
    op.create_table(
        "challenge_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column("username_id", sa.Uuid(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
            name=op.f("challenge_participants_challenge_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("challenge_participants_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["username_id"],
            ["usernames.id"],
            name=op.f("challenge_participants_username_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("challenge_participants_pkey")),
        sa.UniqueConstraint(
            "challenge_id", "username_id", name="uq_participant_username_challenge"
        ),
        sa.UniqueConstraint(
            "user_id", "challenge_id", name="uq_participant_user_challenge"
        ),
    )
    op.create_index(
        op.f("challenge_participants_deleted_at_idx"),
        "challenge_participants",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.String(length=255), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["challenge_participants.id"],
            name=op.f("answers_participant_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("answers_question_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("answers_pkey")),
        sa.UniqueConstraint(
            "participant_id", "question_id", name="uq_participant_question"
        ),
    )
    op.create_index(
        op.f("answers_deleted_at_idx"), "answers", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("answers_deleted_at_idx"), table_name="answers")
    op.drop_table("answers")
    op.drop_index(
        op.f("challenge_participants_deleted_at_idx"),
        table_name="challenge_participants",
    )
    op.drop_table("challenge_participants")
    op.drop_table("usernames")
    op.drop_table("questions")
    op.drop_table("username_mothers")
    op.drop_index(op.f("challenges_deleted_at_idx"), table_name="challenges")
    op.drop_table("challenges")
    # ### end Alembic commands ###
