"""add scopes to refresh_tokens

Revision ID: dd4ca2ff096e
Revises: 91cc57573789
Create Date: 2026-09-11 00:05:46.857827

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd4ca2ff096e"
down_revision: str | Sequence[str] | None = "91cc57573789"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens", sa.Column("scopes", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "scopes")
    # ### end Alembic commands ###
