"""add oauth provider to users

Revision ID: e0bee973af24
Revises: 4f21ac9d7b30
Create Date: 2026-10-02 13:52:42.044097

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0bee973af24"
down_revision: str | Sequence[str] | None = "4f21ac9d7b30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("oauth_provider", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "oauth_provider")
    # ### end Alembic commands ###
